-- OPA Bar & Cafe — QR table ordering
-- 0007_seed_category_images.sql: representative photo per subcategory,
-- sourced from Zillout's shared category-icon library and matched by name.
-- Generated by scripts/generate-category-image-updates.js.
-- 43 of 46 categories matched; the rest
-- (Lemonade, Herbal Tea, Pides) had no good match and keep the UI's icon
-- fallback instead.

update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1765.png' where name = 'Signature Mocktails';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/300.png' where name = 'Signature Cocktails';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/1076_Screenshot%202026-07-01%20154132.png' where name = 'Desserts'; -- Baklava, an actual OPA menu photo, swapped in for the generic stock icon
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/3963.png' where name = 'Whiskey';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/607.png' where name = 'American Whiskey / Bourbon';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/308.png' where name = 'Single Malts';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/3964.png' where name = 'Vodka';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/2743.png' where name = 'Gin';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/253.png' where name = 'Brandy / Cognac';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/3965.png' where name = 'Rum';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1137.png' where name = 'Tequila';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/316.png' where name = 'Liqueurs';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/3966.png' where name = 'Beer';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/35.png' where name = 'Breezer';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/369.png' where name = 'Champagne & Sparkling Wines';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/81.png' where name = 'White Wine';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/185.png' where name = 'Red Wine';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/187.png' where name = 'Rose Wine';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/45.png' where name = 'Shooters';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/86.png' where name = 'Shots & Shot Trays';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1560.png' where name = 'Classic Cocktails';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/192.png' where name = 'LIIT';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1017.png' where name = 'Energy Cocktails';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/2638.png' where name = 'Mixers';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1029.png' where name = 'Mocktails';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1017.png' where name = 'Energy Zone';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1049.png' where name = 'Hot Beverages';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/574.png' where name = 'Cold Coffee';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/576.png' where name = 'Iced Tea';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/729.png' where name = 'Milkshake';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/573.png' where name = 'Tea';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/193.png' where name = 'Fresh Juice';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/796.png' where name = 'Cold Mezze';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/219.png' where name = 'Hot Mezze — Vegetarian';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1052.png' where name = 'Hot Mezze — Non-Vegetarian';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1230.png' where name = 'Salads';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1229.png' where name = 'Soup';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1067.png' where name = 'Grills';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/991.png' where name = 'From the Turkish Grill';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1800.png' where name = 'Freshly Baked Bread Basket';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/95.png' where name = 'Pizzas';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1648.png' where name = 'Main Course';
update public.categories set image_url = 'https://d1hddaam55e99y.cloudfront.net/categoryItem/1095.png' where name = 'Wraps / Savories';
